name: tf2
channels:
  - conda-forge
  - defaults
dependencies:
  - graphviz
  - imageio=2.6.1
  - ipython=7.10.1
  - ipywidgets=7.5.1
  - joblib=0.14.0
  - jupyter=1.0.0
  - matplotlib=3.1.2
  - nbdime=1.1.0
  - nltk=3.4.5
  - numexpr=2.7.0
  - numpy=1.17.3
  - pandas=0.25.3
  - pillow=6.2.1
  - pip
  - py-xgboost=0.90
  - pydot=1.4.1
  - pyopengl=3.1.3b2
  - python=3.7
  - python-graphviz
  - requests=2.22.0
  - scikit-image=0.16.2
  - scikit-learn=0.22
  - scipy=1.3.1
  - tqdm=4.40.0
  - wheel
  - widgetsnbextension=3.5.1
  - pip:
    #- atari-py==0.2.6 # NOT ON WINDOWS YET
    - ftfy==5.7
    - gym==0.15.4
    - opencv-python==4.1.2.30
    - psutil==5.6.7
    - pyglet==1.3.2
    - spacy==2.2.4
    - tensorboard==2.1.1
    #- tensorflow-addons==0.8.3 # NOT ON WINDOWS YET
    #- tensorflow-data-validation==0.21.5 # NOT ON WINDOWS YET
    - tensorflow-datasets==2.1.0
    - tensorflow-estimator==2.1.0
    - tensorflow-hub==0.7.0
    #- tensorflow-metadata==0.21.1 # NOT ON WINDOWS YET
    #- tensorflow-model-analysis==0.21.6 # NOT ON WINDOWS YET
    - tensorflow-probability==0.9.0
    - tensorflow-serving-api==2.1.0 # or tensorflow-serving-api-gpu if gpu
    #- tensorflow-transform==0.21.2 # NOT ON WINDOWS YET
    - tensorflow==2.1.0 # or tensorflow-gpu if gpu
    - tf-agents==0.3.0
    #- tfx==0.21.2 # NOT ON WINDOWS YET
    - transformers==2.8.0
    - urlextract==0.13.0
    #- pyvirtualdisplay # add if on headless server
